### ISSUE TITLE
Puppet.conf setzt lastrunfile nicht

### ISSUE THREAD

**Issue by nce** [vision-it/vision-puppet#1]
Schlaegt der Puppetrun fruehzeitig fehl mit:

```
Error: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /root
Error: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /root
Wrapped exception:
Is a directory @ rb_sysopen - /root
Error: /File[/root]/ensure: change from directory to file failed: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /root
Error: Could not prepare for execution: Got 1 failure(s) while initializing: File[/root]: change from directory to file failed: Could not set 'file' on ensure: Is a directory @ rb_sysopen - /root
```

Ursache ist ein moeglicherweise nicht korrekt gesetzter `lastrunfile` Parameter in `/etc/puppetlabs/puppet/puppet.conf`. Herkunft unklar.

Ref: #294 in Redmine

**Comment by martialblog** [comment]
Hab das mal in den Beaker Test mitaufgenommen. Da wird der String im Template gesetzt und alles passt.
https://github.com/vision-it/vision-puppet/commit/b96c307e9337c6f6c40140e2607c32b010b9e7bd

**Comment by martialblog** [comment]
Fixed 
https://github.com/vision-it/vision-puppet/commit/d125ce4c1113a4960e3e4fc6f43ae57884167ce2
