### ISSUE TITLE
Puppet server pinning

### ISSUE THREAD

**Issue by darkstar42** [vision-it/vision-puppet#2]
At the moment only the Puppet client can be pinned. Allow the _puppetserver_ package to be pinned.

**Comment by darkstar42** [comment]
The new bootstrap already pins the _puppetserver_ package but a change of the version number within the Puppet code will not update the pin.

**Comment by martialblog** [comment]
Already getting pinned:
```
class vision_puppet::server (

  String $version,
```

**Comment by darkstar42** [comment]
nope, that just makes sure that Puppet will upgrade/downgrade the Puppet server to the given version.

For the client there is an extra pinning configuration file:
https://github.com/vision-it/vision-puppet/blob/production/manifests/client.pp#L76

**Comment by martialblog** [comment]
My bad... Yes, we shall do that:

```
  file { '/etc/apt/preferences.d/puppetserver':
    ensure  => present,
    owner   => root,
    group   => root,
        content => "# This file is managed by Puppet; DO NOT EDIT
    Package: puppetserver
    Pin: version ${version}
    Pin-Priority: ${pin_priority}
    "
  }
```

**Comment by martialblog** [comment]
Needs testing:
https://github.com/vision-it/vision-puppet/commit/492875f67424a635bd97c2800ef7541f4a070a09

**Comment by darkstar42** [comment]
Test needs to be updated?

>  Failure/Error: it { should be_installed.with_version('2.4.0-1puppetlabs1') }
>       expected Package "puppetserver" to be installed with version "2.4.0-1puppetlabs1"

**Comment by martialblog** [comment]
Maybe the pinning version needs to be just "2.4.0". I'll have a look at it.

**Comment by darkstar42** [comment]
see #3

**Comment by darkstar42** [comment]
solved
